### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by christopherhastings** [jonluca/resy-api#3]
`[2022-06-10 11:30:02] [info] - skipping available date because of allowed dates flag 
ReferenceError: structuredClone is not defined
    at ResyService.search (file:///root/home/reservations/resy-api-main/src/controllers/ResyService.ts:153:18)
    at ResyService.getAvailableTimesForVenueAndDate (file:///root/home/reservations/resy-api-main/src/controllers/ResyService.ts:230:36)
    at refreshAvailabilityForVenue (file:///root/home/reservations/resy-api-main/src/monitor.ts:85:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Have run it on multiple restaurants and on dates that can be booked manually via the website. 

Finding the restaurant code was best done by searching for text that also included 'Latitude' and rest.com links. 

@jonluca Is structuredClone something you defined?

**Comment by jonluca** [comment]
Structured clone is a new language feature, make sure you're using at least node 17

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
